# Generated by Django 3.2.4 on 2021-07-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='qr_code_link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
