# Generated by Django 3.2.4 on 2021-07-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_qr_code_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='qr_code_link',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
